config/routes.rb
Rails.application.routes.draw do
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'

    get '/signup', to: 'students#new'

    resource :faq, only: [] do
        get :winning
        # get :competitions
    end

    resource :my_notebook, only: [] do
        get :courses_in_progress
        get :courses_completed
        get :saved_for_later
        get :payment_details

        get :competitions_current
        get :competitions_past
        get :competitions_saved

        get "courses_completed/:course_id_token/show_results", 
            to: "my_notebooks#show_results", as: "show_course_results"
        # get "courses_in_progress/:course_id_token/show_results", to: "my_notebooks#show_results"

        get :basic_info
        get :password_and_email
        get :bio_and_qualifications
        get :messages
        
        namespace :basic_info do 
          patch "update-display-name"
          patch "update-password"
          patch "update-email"
          patch "disable-account"
          patch "delete-account"
          get "delete-account", to: "my_notebooks#show_delete_account"
          get "show-delete-modal"
        end
    end

    root to: 'competitions#index'

    resources :notifications, only: [] do
        member do 
            patch :read          
        end
    end

    resources :video_submissions, shallow: true, only: [] do
        resources :comments, shallow: true, only: [:create, :destroy, :update] do 
          member do 
              post :create_reply
              post :upvote
              delete :upvote, to: "comments#remove_upvote"
          end
        end
    end

    resources :competitions, only: [:index, :show] do
        collection do
            get :paid
            get :volunteer
        end
        member do 
            post :join
            delete :withdraw
        end
        resource :save_event, only: [:create, :destroy]
        resources :comments, shallow: true, only: [:create] do 
          #member do 
          #    post :create_reply
          #end
        end

        resources :video_submissions, shallow: true, only: [:show, :create, :edit, :update, :destroy] do
          collection do
              post :upload_video
          end

          member do 
              patch :upload_video
              post :upvote
              delete :upvote, to: "video_submissions#remove_upvote"
          end
        end
    end

    resources :courses, param: :course_token, only: [:index, :show] do
       member do

          post "like", to: "api/v1/like_event#create_like"
          post "remove_like", to: "api/v1/like_event#destroy"

          post "dislike", to: "api/v1/like_event#create_dislike"
          post "remove_dislike", to: "api/v1/like_event#destroy"

          post "load_slider_notes", to: "courses#load_slider_notes"
       end
    end

    resources :courses, param: :token, only: [] do
       resources :comments, shallow: true, only: [:create, :destroy]

       resource :save_event, only: [:create, :destroy]
    end

    get "/subjects/:subject/", to: "courses#index_by_subject", as: "index_by_subject"
    get "/courses/:course/", to: "courses#index_by_course", as: "index_by_course"

    get '/account_recovery', to: 'students#account_recovery'

    # get "/premium", to: "subscriptions#offer"
    # get "/payment_success", to: "subscriptions#payment_success"

    resource :subscription, only: [] do
        collection do 
            get :show
            post :create
            delete :destroy, path: "/unsubscribe"
            post :update_card
        end
    end

    get "/checkout", to: "subscriptions#checkout", as: "checkout"
    # post "/checkout_session", to: "shopping_cart#checkout_session", as: "checkout_session"

    # post '/checkout/pay', to: 'transaction#create', as: "transaction_create" 
    # get '/checkout/success', to: 'transaction#success', as: "transaction_success"
    # get '/checkout/show', to: 'transaction#show', as: "transaction_show"

    resources :students, param: :student_username, only: [:new, :create, :index] do
      member do
        get :about
        patch :update_photo
        post :billing_address, to: "billing_addresses#create" 
        patch :billing_address, to: "billing_addresses#update"

        post :bank_account, to: "bank_accounts#create"
        patch :bank_account, to: "bank_accounts#update"
      end
    end

    get "/students/not_me/:email_code", to: "students#not_me", as: "not_me"
    get "/students/new_reset_password/:email_code", to: "students#new_reset_password", as: "new_reset_password"

    namespace :api do
      namespace :v1 do
        get 'accounts/:student_id/verify_email', to: 'accounts#verify_email', as: 'verify_email'
        post 'accounts/:student_id/verify_email', to: 'accounts#verify_email', as: 'pin_verify_email'
        get 'accounts/:student_id/check_username_available', to: 'accounts#check_username_available'
        get 'accounts/:student_id/change_email', to: 'accounts#change_email'

        post 'accounts/recover_username', to: 'accounts#recover_username', as: 'recover_username'
        post 'accounts/reset_password', to: 'accounts#reset_password', as: 'reset_password'
        patch 'accounts/create_reset_password', to: 'accounts#create_reset_password', as: 'create_reset_password' # since this is an update
        post 'accounts/not_me_confirmation', to: 'accounts#not_me_confirmation', as: 'not_me_confirmation'

        get 'accounts/reset_password_confirmation', to: 'accounts#reset_password_confirmation', as: 'reset_password_confirmation'
        get 'accounts/not_me', to: 'accounts#not_me', as: 'not_me'
      end
    end
  # go to session controller to switch to dashboard
  # get '/switch_to_dashboard', to: 'sessions#switch_to_dashboard', as: 'switch_to_dashboard'
  # create a subdomain for a student dashboard
  # replacement for generic show route

  constraints :subdomain => 'dashboard' do

    namespace(:dashboard, :path => '/') do

      delete '/logout', to: 'sessions#destroy', as: 'logout'

      get 'orders/new'
      get 'orders/create'
      get 'orders/index'
      post '/courses', to: "private_courses#create"
      patch "/lessons/intro_summary", to: "lessons#update_intro_summary", as: 'update_intro_summary'

      resources :students, controller: :student_admins, param: :student_username, only: [] do
        member do
          patch :update_email
          get :profile
        end
      end

      resources :courses, controller: :private_courses, param: :course_id_token, only: [] do
          member do
            patch :update_module_order
            patch :update_lesson_order # since many modules are affected
          end
      end

      resources :courses, param: :id_token, only: [] do
          resources :module_parts, param: :module_id, shallow: true, only: [:create, :update, :destroy] do
          end
      end

      resources :modules, controller: :module_parts, only: [] do 
            resources :lessons, param: :lesson_id, shallow: true, only: [:create, :edit, :update, :destroy] do
            end
      end

      resources :lessons, only: [] do
            resources :mc_quiz_questions, shallow: true, only: [:create, :edit, :update, :destroy] do
            end
      end

      resources :video_submissions, only: [], shallow: true do
        member do 
          patch :rate
        end
      end

      resources :students, controller: :student_admins, param: :username, only: [] do

            get :payment_history, to: "student_admins#show_payment_history"

            get :comments

            resources :competitions, controller: :private_competitions, except: [:show], shallow: true do
                collection do
                  post :upload_video
                end

                member do 
                  get :video_submissions
                  patch :announce_winners
                end
            end

            resources :courses, controller: :private_courses, param: :course_id_token, only: [], shallow: true do
              collection do
                get :courses, path: "/", as: "content"

                get "/new", to: "private_courses#courses"
                post :create, path: "/"
              end

              member do
                # all options in the tabs for courses.
                get :edit # first option
                get :analytics
                get :design
                get :intro_summary
                # get :comments second option, view comments.

                patch :update, path: "/"
                delete :destroy, path: "/" # last option
                get :delete
              end
            end

            #resource :my_drive, controller: :private_notes, only: [], shallow: true do
            #  collection do
            #    get "/", to: "private_notes#my_drive"
            #    post :load_slider_notes, as: "slider"
            #  end
            #end
      end

    # get :notes, on: :member
      #resources :student_admins, only: [:show, :edit, :update, :destroy]
    end
  end

  constraints :subdomain => 'learning' do
      namespace(:learning, :path => '/') do
          resources :courses, param: :id_token, only: [] do
              patch :update_completed

              get "/lessons/:learnable_type/:learnable_id", to: "lessons#show",
                  as: "lesson", constraints: { 
                  learnable_type: /(lesson-text|lesson-video|mc-quiz|assignment-video)/ 
              }

              get "/lessons/:learnable_type/:learnable_id/:question_id", to: "lessons#show_quiz_question",
                  as: "quiz_question", constraints: { 
                  learnable_type: /(mc-quiz)/ 
              }
              #get "/lesson-texts/:learnable_id", to: "lessons#show_reading", as: "reading"
              #get "/mc-questions/:learnable_id", to: "lessons#show_mc_question", as: "question"

app/models/competition.rb
class Competition < ApplicationRecord
  belongs_to :student

  has_rich_text :requirements
  has_rich_text :description

  has_one_attached :video, dependent: :destroy
  has_many :video_submissions, dependent: :destroy
  has_many :competition_events, dependent: :destroy
  has_many :contestants, through: :competition_events, source: :student

  has_many :notifications, as: :notifiable

  has_many :comments, as: :commentable

  has_many :save_events, as: :saveable, dependent: :destroy

  validates :prize_money, :numericality => { :greater_than_or_equal_to => 0 }
  
  # validate :valid_deadline, :on => :update

  def valid_deadline
      if (self.deadline_date < Date.current)
          errors.add(:deadline_date, "must not be earlier than the current date")
      end
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :authenticate, only: [:join]

  def index
    current_date = Date.current
    @current_competitions = Competition.where(deadline_date: current_date..) # deadline is today, tomorrow or after.
    @current_videos = @current_competitions.map(&:video)

    @past_competitions = Competition.where(deadline_date: ...current_date) # deadline is yesterday or before
    @past_videos = @past_competitions.map(&:video)

    respond_to do |format|
      format.html
      format.js
    end
  end

  #  def paid
  #    @paid_competitions = Competition.where(has_prize: true)
  #    @videos = @paid_competitions&.map(&:video)

  #    respond_to do |format|
        # format.html
  #      format.js
  #    end
  #  end

  #  def volunteer
  #    @volunteer_competitions = Competition.where(has_prize: false)
  #    @videos = @volunteer_competitions&.map(&:video)

  #    respond_to do |format|
        # format.html
  #      format.js
  #    end
  #  end

  def show
    @competition = Competition.find(params[:id])
    deadline_date_array = @competition.deadline_date.strftime("%Y-%m-%d").split("-") 
    results_date_array = @competition.results_date.strftime("%Y-%m-%d").split("-") 
    # deadline_time_array = @competition.deadline_time.strftime("%H:%M").split(":")

    @utc_deadline = Time.utc(deadline_date_array[0], deadline_date_array[1], deadline_date_array[2], 23, 59)
    @utc_results_date = Time.utc(results_date_array[0], results_date_array[1], results_date_array[2], 23, 59)

    #offset = (current_student&.time_zone || "+00:00") # assume the user is in sydney
    #@local_deadline = utc_deadline.getlocal(offset)

    @client = @competition.student

    if logged_in_as_student?
        @student_upvoted_comment_ids = current_student&.upvotes.where(upvoteable_type: "Comment").pluck(:upvoteable_id)
        @competition_event = CompetitionEvent.exists?(student_id: current_student&.id, competition_id: params[:id]) ?
                             CompetitionEvent.find_by(student_id: current_student&.id, competition_id: params[:id]) : nil    
        if (VideoSubmission.exists?(student_id: current_student&.id, competition_id: params[:id]))                             
            @video_submission = VideoSubmission.find_by(student_id: current_student&.id, competition_id: params[:id])             
            @video_submission_video = @video_submission.video
        else 
            @video_submission = nil            
            @video_submission_video = nil
        end
    else  
        @competition_event = nil
    end
    @save_event = SaveEvent.exists?(student_id: current_student&.id, saveable_type: "Competition",
                saveable_id: params[:id]) ? SaveEvent.find_by(student_id: current_student&.id, saveable_type: "Competition",
                saveable_id: params[:id]) : nil               

    @requirements = @competition.requirements

    all_comments = @competition.comments.order(created_at: :desc)
    my_comments = all_comments.where(student_id: current_student&.id)
    other_comments = all_comments.excluding(my_comments)

    @comments = my_comments + other_comments 

    if @comments.present?
        @comment_authors = @comments.map(&:student)
        @comment_replies = @comments.map(&:comments)
        @comment_reply_authors = @comment_replies.map{ |collection| collection.map(&:student) if collection.present? }
    end

    @array_of_contestant_ids = @competition.competition_events.pluck(:student_id)
    
    @video = @competition.video

    # code for loading all of the video submissions for a competition
    @competition_video_submissions = @competition.video_submissions
    @video_submission_submitters = @competition_video_submissions.map(&:student)
    @competition_submission_videos = @competition_video_submissions.map(&:video)

    submission_placeholder_count = 4 - (@competition_video_submissions.count % 4)
    @submission_placeholders = (submission_placeholder_count == 4) ? [] : [*1..submission_placeholder_count]

    respond_to do |format|
      format.html
    end
  end

  # competition event
  def join
    @competition = Competition.find(params[:id])

    @msg = "You have already joined the competition"
    
    if (CompetitionEvent.exists?(student_id: current_student&.id, competition_id: @competition.id)) 
        @joined = false
    else 
        new_comp = CompetitionEvent.new(student_id: current_student&.id, competition_id: @competition.id)
        @joined = new_comp.save
        if (@joined)
           @msg = "You have joined the competition"
        else 
           @msg = "Something went wrong"
        end
    end

    respond_to do |format|
      format.js
    end
  end

  def withdraw
    @competition = Competition.find(params[:id])
    
    if (CompetitionEvent.exists?(student_id: current_student&.id, competition_id: @competition.id)) 
        CompetitionEvent.find_by(student_id: current_student&.id, competition_id: @competition.id).destroy!
        @msg = "You withdrew from #{@competition.title}"
    else 
        @msg = "You have not joined the selected competition previously"
    end

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_index_competitions.html.erb
<div class="columns is-flex-wrap-wrap is-flex m-0 p-0">
  <% if competitions.present? %>
      <% competitions.each_with_index do |competition, index| %>
        <div class="column mb-5 p-0 is-flex-grow-0 card-holder">
            <%= link_to competition_url(subdomain: false, id: competition.id), class: "" do %>
                  <div class="card-image">
                    <figure class="image w-100">
                        <% if (videos.present? && videos[index].previewable?) %>
                            <%= image_tag videos[index].preview(resize_to_limit: [210, 150]),  class:"course_image_thumbnail border-radius-none" %>
                        <% else %>
                            <%= image_tag(image_path("image_placeholder.png"), class:"course_image_thumbnail obj-cover border-radius-none") %>
                        <% end %>
                    </figure>
                  </div>
                  <div class="card-content p-0">
                      <div class="content p-2">
                        <div class="content-title mb-0"><%= competition.title %></div>
                        <div class="is-flex is-align-items-center mt-1">
                            <i class="far fa-user pr-1"></i>
                            <span class="content-subtitle">Justin</span>
                        </div>
                      </div>
                  </div>
            <% end %>
        </div>
      <% end %>
  <% else %>
        <div class="column bg-white">
            <div class="w-100 mt-5rem is-flex is-justify-content-center 
                        is-flex-direction-column is-align-items-center">
                <figure class="image is-192x192">
                    <%= image_tag(image_path("video-editing.png"), class: "h-min-content opacity-50") %>
                </figure>
                <p class="mb-2 is-size-5">This section has no competitions running.</p>
            </div>
        </div>
  <% end %>
</div>

app/views/competitions/index.html.erb
<div id="main_panel" class="flex-grow">
  <section class="section pt-4 pb-2 h-100" id="index_competitions_container">
    <div class="container">
      <p class="title is-2 pt-4">Online video editing competitions</p>
      <div class="secondary_header">
          Current competitions
      </div>
      <div class="competition-videos-holder">
          <%= render "index_competitions", competitions: @current_competitions, videos: @current_videos %>
      </div>
      <div class="secondary_header">
          Past competitions
      </div>
      <div class="competition-videos-holder">
          <%= render "index_competitions", competitions: @past_competitions, videos: @past_videos %>
      </div>
    </div>
  </section>
</div>

  <!--
           <div class="mx-0 pb-2" id="subject_tag_bar">
              <div class="tabs">
                <ul>  
                    <li class="is-active">
                        <%= link_to "Paid Competitions", paid_competitions_url(subdomain: false), remote: true %>
                    </li>
                    <li class="">
                        <%= link_to "Volunteer Competitions", volunteer_competitions_url(subdomain: false), remote: true %>
                    </li>
                    <li class="is-hidden">
                        <%= link_to "Learning projects", courses_url(subdomain: false), remote: true %>
                    </li>
                </ul>
             </div>
           </div>
      -->

app/views/competitions/index.js.erb
$("#home-index-holder").html("<%= j (render partial: 'competitions/index_competitions', 
                              locals: { competitions: @competitions, videos: @videos } ) %>");

app/views/competitions/join.js.erb
var joined = <%= @joined %>;
var competition_header_box = $("section#header_box");

if (joined) {
    competition_header_box.find("#join_competition_link").addClass("is-hidden");
    competition_header_box.find("#upload_video_submission_button").removeClass("is-hidden");
}

var snackbar = document.createElement("div");
$(snackbar).attr("id", "snackbar");
$(snackbar).text("<%= @msg %>");
$("body").append($(snackbar));
$(snackbar).addClass("show");
setTimeout(
  function(){
    $(snackbar).removeClass("show");
  }, 4000);

app/views/competitions/paid.js.erb
$("#home-index-holder").html("<%= j (render partial: 'competitions/index_competitions',
      locals: { competitions: @paid_competitions, videos: @videos } ) %>");

app/views/competitions/volunteer.js.erb
$("#home-index-holder").html("<%= j (render partial: 'competitions/index_competitions',
      locals: { competitions: @volunteer_competitions, videos: @videos } ) %>");

app/views/competitions/withdraw.js.erb
$("#my-notebook-page-holder").find(".card[data-competition-id='<%= @competition.id %>']").remove();

var snackbar = document.createElement("div");
$(snackbar).attr("id", "snackbar");
$(snackbar).text("<%= @msg %>");
$("body").append($(snackbar));
$(snackbar).addClass("show");
setTimeout(
  function(){
    $(snackbar).removeClass("show");
  }, 4000);