config/routes.rb
Rails.application.routes.draw do
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'

    get '/signup', to: 'students#new'

    resource :faq, only: [] do
        get :winning
        # get :competitions
    end

    resource :my_notebook, only: [] do
        get :courses_in_progress
        get :courses_completed
        get :saved_for_later
        get :payment_details

        get :competitions_current
        get :competitions_past
        get :competitions_saved

        get "courses_completed/:course_id_token/show_results", 
            to: "my_notebooks#show_results", as: "show_course_results"
        # get "courses_in_progress/:course_id_token/show_results", to: "my_notebooks#show_results"

        get :basic_info
        get :password_and_email
        get :bio_and_qualifications
        get :messages
        
        namespace :basic_info do 
          patch "update-display-name"
          patch "update-password"
          patch "update-email"
          patch "disable-account"
          patch "delete-account"
          get "delete-account", to: "my_notebooks#show_delete_account"
          get "show-delete-modal"
        end
    end

    root to: 'competitions#index'

    resources :notifications, only: [] do
        member do 
            patch :read          
        end
    end

    resources :video_submissions, shallow: true, only: [] do
        resources :comments, shallow: true, only: [:create, :destroy, :update] do 
          member do 
              post :create_reply
              post :upvote
              delete :upvote, to: "comments#remove_upvote"
          end
        end
    end

    resources :competitions, only: [:index, :show] do
        collection do
            get :paid
            get :volunteer
        end
        member do 
            post :join
            delete :withdraw
        end
        resource :save_event, only: [:create, :destroy]
        resources :comments, shallow: true, only: [:create] do 
          #member do 
          #    post :create_reply
          #end
        end

        resources :video_submissions, shallow: true, only: [:show, :create, :edit, :update, :destroy] do
          collection do
              post :upload_video
          end

          member do 
              patch :upload_video
              post :upvote
              delete :upvote, to: "video_submissions#remove_upvote"
          end
        end
    end

    resources :courses, param: :course_token, only: [:index, :show] do
       member do

          post "like", to: "api/v1/like_event#create_like"
          post "remove_like", to: "api/v1/like_event#destroy"

          post "dislike", to: "api/v1/like_event#create_dislike"
          post "remove_dislike", to: "api/v1/like_event#destroy"

          post "load_slider_notes", to: "courses#load_slider_notes"
       end
    end

    resources :courses, param: :token, only: [] do
       resources :comments, shallow: true, only: [:create, :destroy]

       resource :save_event, only: [:create, :destroy]
    end

    get "/subjects/:subject/", to: "courses#index_by_subject", as: "index_by_subject"
    get "/courses/:course/", to: "courses#index_by_course", as: "index_by_course"

    get '/account_recovery', to: 'students#account_recovery'

    # get "/premium", to: "subscriptions#offer"
    # get "/payment_success", to: "subscriptions#payment_success"

    resource :subscription, only: [] do
        collection do 
            get :show
            post :create
            delete :destroy, path: "/unsubscribe"
            post :update_card
        end
    end

    get "/checkout", to: "subscriptions#checkout", as: "checkout"
    # post "/checkout_session", to: "shopping_cart#checkout_session", as: "checkout_session"

    # post '/checkout/pay', to: 'transaction#create', as: "transaction_create" 
    # get '/checkout/success', to: 'transaction#success', as: "transaction_success"
    # get '/checkout/show', to: 'transaction#show', as: "transaction_show"

    resources :students, param: :student_username, only: [:new, :create, :index] do
      member do
        get :about
        patch :update_photo
        post :billing_address, to: "billing_addresses#create" 
        patch :billing_address, to: "billing_addresses#update"

        post :bank_account, to: "bank_accounts#create"
        patch :bank_account, to: "bank_accounts#update"
      end
    end

    get "/students/not_me/:email_code", to: "students#not_me", as: "not_me"
    get "/students/new_reset_password/:email_code", to: "students#new_reset_password", as: "new_reset_password"

    namespace :api do
      namespace :v1 do
        get 'accounts/:student_id/verify_email', to: 'accounts#verify_email', as: 'verify_email'
        post 'accounts/:student_id/verify_email', to: 'accounts#verify_email', as: 'pin_verify_email'
        get 'accounts/:student_id/check_username_available', to: 'accounts#check_username_available'
        get 'accounts/:student_id/change_email', to: 'accounts#change_email'

        post 'accounts/recover_username', to: 'accounts#recover_username', as: 'recover_username'
        post 'accounts/reset_password', to: 'accounts#reset_password', as: 'reset_password'
        patch 'accounts/create_reset_password', to: 'accounts#create_reset_password', as: 'create_reset_password' # since this is an update
        post 'accounts/not_me_confirmation', to: 'accounts#not_me_confirmation', as: 'not_me_confirmation'

        get 'accounts/reset_password_confirmation', to: 'accounts#reset_password_confirmation', as: 'reset_password_confirmation'
        get 'accounts/not_me', to: 'accounts#not_me', as: 'not_me'
      end
    end
  # go to session controller to switch to dashboard
  # get '/switch_to_dashboard', to: 'sessions#switch_to_dashboard', as: 'switch_to_dashboard'
  # create a subdomain for a student dashboard
  # replacement for generic show route

  constraints :subdomain => 'dashboard' do

    namespace(:dashboard, :path => '/') do

      delete '/logout', to: 'sessions#destroy', as: 'logout'

      get 'orders/new'
      get 'orders/create'
      get 'orders/index'
      post '/courses', to: "private_courses#create"
      patch "/lessons/intro_summary", to: "lessons#update_intro_summary", as: 'update_intro_summary'

      resources :students, controller: :student_admins, param: :student_username, only: [] do
        member do
          patch :update_email
          get :profile
        end
      end

      resources :courses, controller: :private_courses, param: :course_id_token, only: [] do
          member do
            patch :update_module_order
            patch :update_lesson_order # since many modules are affected
          end
      end

      resources :courses, param: :id_token, only: [] do
          resources :module_parts, param: :module_id, shallow: true, only: [:create, :update, :destroy] do
          end
      end

      resources :modules, controller: :module_parts, only: [] do 
            resources :lessons, param: :lesson_id, shallow: true, only: [:create, :edit, :update, :destroy] do
            end
      end

      resources :lessons, only: [] do
            resources :mc_quiz_questions, shallow: true, only: [:create, :edit, :update, :destroy] do
            end
      end

      resources :video_submissions, only: [], shallow: true do
        member do 
          patch :rate
        end
      end

      resources :students, controller: :student_admins, param: :username, only: [] do

            get :payment_history, to: "student_admins#show_payment_history"

            get :comments

            resources :competitions, controller: :private_competitions, except: [:show], shallow: true do
                collection do
                  post :upload_video
                end

                member do 
                  get :video_submissions
                  patch :announce_winners
                end
            end

            resources :courses, controller: :private_courses, param: :course_id_token, only: [], shallow: true do
              collection do
                get :courses, path: "/", as: "content"

                get "/new", to: "private_courses#courses"
                post :create, path: "/"
              end

              member do
                # all options in the tabs for courses.
                get :edit # first option
                get :analytics
                get :design
                get :intro_summary
                # get :comments second option, view comments.

                patch :update, path: "/"
                delete :destroy, path: "/" # last option
                get :delete
              end
            end

            #resource :my_drive, controller: :private_notes, only: [], shallow: true do
            #  collection do
            #    get "/", to: "private_notes#my_drive"
            #    post :load_slider_notes, as: "slider"
            #  end
            #end
      end

    # get :notes, on: :member
      #resources :student_admins, only: [:show, :edit, :update, :destroy]
    end
  end

  constraints :subdomain => 'learning' do
      namespace(:learning, :path => '/') do
          resources :courses, param: :id_token, only: [] do
              patch :update_completed

              get "/lessons/:learnable_type/:learnable_id", to: "lessons#show",
                  as: "lesson", constraints: { 
                  learnable_type: /(lesson-text|lesson-video|mc-quiz|assignment-video)/ 
              }

              get "/lessons/:learnable_type/:learnable_id/:question_id", to: "lessons#show_quiz_question",
                  as: "quiz_question", constraints: { 
                  learnable_type: /(mc-quiz)/ 
              }
              #get "/lesson-texts/:learnable_id", to: "lessons#show_reading", as: "reading"
              #get "/mc-questions/:learnable_id", to: "lessons#show_mc_question", as: "question"

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  # show is for displaying details of the subscription once student upgraded.
  def show
  end

  def payment_success
  end

  # create is for clicking the submit/pay button on the checkout form.
  def create
      # aka referring to myself via my square account.
      client = Square::Client.new(
          access_token: "EAAAEBDCEmrU0PdNO12GAcmOyFqNcMy43wAIMfwMCPA9HYjyefj08D5Yey281oE_",
          environment: "sandbox"
      )
      # create a subscription by sending the square card nonce to square subscriptions api.
      # 1. Create a customer - providing username, first and last name.
      # name_array = credit_card_params[:name].split(" "). Not needed since first and last name saved when account first made.

      first_result = client.customers.create_customer(
          body: {
            idempotency_key: SecureRandom.uuid,
            given_name: credit_card_params[:first_name],
            family_name: credit_card_params[:last_name],
            email_address: current_student.email
          }
      )

      if first_result.success?
          puts first_result.data
          customer_id = first_result.data.customer[:id]   

          second_result = client.cards.create_card(
              body: {
                idempotency_key: SecureRandom.uuid,
                source_id: credit_card_params[:card_nonce], # "cnon:card-nonce-ok"
                card: {
                    cardholder_name: credit_card_params[:cardholder_name],
                    #billing_address: {
                    #  address_line_1: "500 Electric Ave",
                    #  address_line_2: "Suite 600",
                    #  locality: "New York",
                    #  administrative_district_level_1: "NY",
                    #  postal_code: "94103",
                    #  country: "AU"
                    #},
                    customer_id: customer_id,
                    # i.e. use the id_token of student and the current time and
                    # dates as in db migrations to create alternate reference.
                    reference_id: "#{current_student.id_token}:#{DateTime.now.strftime('%Y%m%d%H%M')}"
                }
              }
          )

          if second_result.success?
              puts second_result.data
              card_id = second_result.data.card[:id] 

              third_result = client.catalog.upsert_catalog_object( 
                    body: {
                      idempotency_key: SecureRandom.uuid,
                      object: {
                        type: "SUBSCRIPTION_PLAN",
                        id: "#premium_plan",
                        subscription_plan_data: {
                          name: "Notebank premium membership",
                          phases: [
                            {
                              cadence: "MONTHLY",
                              recurring_price_money: {
                                amount: 999,
                                currency: "AUD"
                              }
                            }
                          ]
                        }
                      }
                    }
              )

              if third_result.success?
                  puts third_result.data
                  subscription_plan_id = third_result.data.catalog_object[:id]

                  fourth_result = client.subscriptions.create_subscription(
                      body: {
                          idempotency_key: SecureRandom.uuid,
                          location_id: "LMX6TRKH0S295", # aka the location id
                          plan_id: subscription_plan_id,
                          customer_id: customer_id,
                          card_id: card_id
                      }
                  )

                  if fourth_result.success?
                    puts fourth_result.data
                    # subscription has now been created, so update the student model.
                    current_student.update!(is_subscribed: true)

                    success = true

                  elsif fourth_result.error?
                    warn fourth_result.errors
                    @error = fourth_result.errors
                  end
                                    
              elsif third_result.error?
                warn third_result.errors
                @error = third_result.errors
              end

          elsif second_result.error?
              warn second_result.errors
              @error = second_result.errors
          end   

      elsif first_result.error?
          warn first_result.errors
          @error = first_result.errors
      end 
      
      respond_to do |format|
          if success
            format.html { render "payment_success" }
          else
            # must be an error. 
            format.js { render "payment_error" }
          end
      end
  end

  def offer # premium page
    if !logged_in_as_student?
        # if the user is a guest wants to upgrade to premium, redirect to same page after login.
        if (premium_params[:nbp] == "guest")
            cookies[:referer] = { value: request.url, domain: ".#{Notebank::DOMAIN}" }
            redirect_to login_url(subdomain: false)
        end
    else
        # if logged_in as a student, but redirected to page to access a premium course.
        # display the premium course and save course_url so to redirect back to after upgrading to premium.
        if (premium_params[:course_id_token].present? && Course.exists?(id_token: premium_params[:course_id_token]))
            @premium_course = Course.find_by(id_token: premium_params[:course_id_token])
            @course_designer = @premium_course.student
            # store for later redirect after payment successful.
            cookies[:premium_referer] = { value: course_url(course_token: premium_params[:course_id_token]), domain: ".#{Notebank::DOMAIN}" }
        end
        # so that those logged in already and those logged out with 
        # no special query can access page directly.
    end

    respond_to do |format|
        format.html
    end
  end

  # checkout is for displaying the checkout form.
  def checkout
    respond_to do |format|
      format.html
    end
  end

  def destroy
  end

  def update_card
  end

  private 

  def premium_params
      params.permit(:nbp, :course_id_token)
  end

  def credit_card_params
      params.fetch(:subscription).permit(:first_name, :last_name, :cardholder_name, :card_nonce)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/checkout.html.erb
<div class="section py-0 w-100" id="checkout_container">
    <div class="mw-60rem has-background-white p-5">
        <div class="container">
            <h2 class="title">Checkout</h2>
            <hr class="darker-divider">
        </div>
        <div class="container">
            <div class="columns my-0 pt-3">
                <section class="column is-flex-grow-1">
                        <div class="card basic-info-card mb-5">
                            <div class="card-content p-0">
                                <div class="checkout-card-heading px-4 py-2 is-flex is-justify-content-space-between">
                                    <span class="is-size-5">Basic info</span>
                                </div>
                                <div class="px-4 pt-3 pb-0 container border-top-gainsboro is-flex is-flex-wrap-wrap">
                                    <div class="field half is-flex-grow-1">
                                        <label class="label">First name</label>
                                        <div class="control">
                                            <input id="first_name_input" type="text">
                                        </div>
                                    </div>
                                    <div class="field half is-flex-grow-1">
                                        <label class="label">Last name</label>
                                        <div class="control">
                                            <input id="last_name_input" type="text">
                                        </div>
                                    </div>
                                </div>
                            </div>
                    </div>
                    <div class="card payment-card mb-5">
                            <div class="card-content p-0">
                            <div class="checkout-card-heading px-4 py-2 is-flex is-justify-content-space-between">
                                <span class="is-size-5">Card payment details</span>
                                <!-- <span class="has-text-link is-clickable is-hidden" id="change_card_details">Change</span> -->
                            </div>
                            <div class="px-4 py-3 container border-top-gainsboro">
                                <div id="card_detail_holder" class="is-hidden is-flex is-align-items-center">
                                    <img alt="Visa" title="Visa" data-card="visa" class="is-hidden" src="https://public-assets.envato-static.com/assets/buying/financial-institutes/visa-75b463620dc6ff97f4a2e44bdbed46ce45822fb161f7beeebe9ffecf3c8b1a01.svg" width="48px" height="30px">
                                    <img alt="MasterCard" title="MasterCard" data-card="mastercard" class="is-hidden" src="https://public-assets.envato-static.com/assets/buying/financial-institutes/mastercard-914fbf5aa6aa3a3cb192fde73953ce4e3cfcbf8bc568fb498c01da0de267e30b.svg" width="48px" height="30px">
                                    <%= image_tag(image_path("american-express.png"), class: "is-hidden height-30px", data: { card: "american_express" }) %>
                                    <span class="ml-5 last_digits"></span>
                                </div>
                                <div id="form-container" class="is-flex is-flex-wrap-wrap is-justify-content-end">
                                    <div id="card-error-notification" class="w-100 py-2 mb-4 notification is-danger is-light is-hidden">
                                    </div>
                                    <div class="field w-100">
                                        <label class="label">Cardholder Name</label>
                                        <div class="control">
                                            <input id="cardholder_name_input" type="text">
                                        </div>
                                    </div>
                                    <div class="field w-100">
                                        <label class="label">Card Number</label>
                                        <div class="control">
                                            <div id="sq-card-number" class=""></div>
                                        </div>
                                    </div>
                                    <div class="fields">
                                        <div class="field third">
                                            <label class="label">Expiry</label>
                                            <div class="control">
                                                <div class="" id="sq-expiration-date"></div>
                                            </div>
                                        </div>
                                        <div class="field third">
                                            <label class="label">CVV</label>
                                            <div class="control">
                                                <div class="" id="sq-cvv"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="third is-hidden" id="sq-postal-code"></div>
                                    <div class="is-flex is-justify-content-space-between w-100 form-container">
                                        <div class="card_icons_holder is-flex is-align-items-center">
                                            <img alt="Visa" title="Visa" class="mr-2" src="https://public-assets.envato-static.com/assets/buying/financial-institutes/visa-75b463620dc6ff97f4a2e44bdbed46ce45822fb161f7beeebe9ffecf3c8b1a01.svg" width="48px" height="30px">
                                                <img alt="MasterCard" title="MasterCard" class="mr-2" src="https://public-assets.envato-static.com/assets/buying/financial-institutes/mastercard-914fbf5aa6aa3a3cb192fde73953ce4e3cfcbf8bc568fb498c01da0de267e30b.svg" width="48px" height="30px">
                                                <%= image_tag(image_path("american-express.png"), class: "mr-2", size: "48x30") %>
                                        </div>
                                    <div class="buttons">
                                        <button id="sq-creditcard" type="button" 
                                        class="w-min-content button is-link">
                                        Confirm Payment</button> <!-- sq-credit-card -->
                                    </div>
                                    </div>
                                </div>
                                <%= form_with scope: :subscription, url: subscription_url(subdomain: false), id: "create-subscription-form" do |f| %>           
                                        <%= f.hidden_field :first_name %>
                                        <%= f.hidden_field :last_name %>
                                        <%= f.hidden_field :cardholder_name %>
                                        <%= f.hidden_field :card_nonce %>
                                <% end %>
                            </div>
                            </div>
                    </div>
                </section>
                <section class="column is-two-fifths is-flex-grow-0">
                    <div class="card mb-5">
                        <div class="card-content p-0">
                            <div class="checkout-card-heading px-4 py-2">
                                <span class="is-size-5">Notebank Premium Subscription</span>
                            </div>
                            <div class="container border-top-gainsboro">
                                <div class="columns m-0 p-4">
                                    <div class="column is-one-third p-0" id="premium-logo-holder">
                                        <span class="logo is-size-5">Premium</span>
                                    </div>
                                    <div class="column is-flex-grow-1 success_details py-0">
                                        <p>Unlimited access to all videos on video production</p>
                                    </div>
                                </div>
                            </div>
                            <hr class="darker-divider mx-4">
                            <div class="container p-4">
                                <div class="is-flex is-justify-content-space-between mb-4">
                                    <span>No commitment. Cancel anytime.</span>
                                </div>
                                <div class="is-flex is-justify-content-space-between">
                                    <span>Monthly subscription:</span>
                                    <div class="is-flex has-text-weight-bold"> 
                                        <span>$9.99</span>
                                        <span class="text-secondary">/per month</span>
                                    </div>
                                </div>
                                <div class="is-flex is-justify-content-space-between">
                                    <span>Total due:</span>
                                    <div class="is-flex has-text-weight-bold"> 
                                        <span>AU $9.99</span>
                                    </div>
                                </div>
                            </div>
                            <hr class="darker-divider mx-4">
                            <div class="container p-4">
                                <div class="is-flex is-justify-content-space-between">
                                    <p class="text-secondary">
                                        Payments are charged on a monthly, recurring basis. 
                                        If you choose to end your subscription, that means your card
                                        will not be charged afterwards for the upcoming month.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>
<%= javascript_pack_tag "sqPaymentForm" %>

app/views/subscriptions/create.html.erb
<h1>Subscriptions#create</h1>
<p>Find me in app/views/subscriptions/create.html.erb</p>

app/views/subscriptions/destroy.html.erb
<h1>Subscriptions#destroy</h1>
<p>Find me in app/views/subscriptions/destroy.html.erb</p>

app/views/subscriptions/offer.html.erb
<section id="premium-plan-section" class="hero is-medium">
    <div class="hero-body is-flex is-flex-direction-column is-align-items-center">        
        <figure class="<%= @premium_course ? 'image mb-4' : 'image' %>">
            <%= image_tag(image_path("notebank_premium_logo.png"), class: "") %>
        </figure>
        <% if @premium_course %>
                <div class="card m-4 is-flex" data-course-id-token="<%= @premium_course.id_token %>">
                    <div class="card-image w-12rem">
                        <figure class="image">
                            <span class="is-text-align-center pdf_placeholder">Image loading...</span>
                            <% if @premium_course.image.representable? %>
                                <%= image_tag(@premium_course.image.representation(resize_to_fill: [840,600]), class:"course_image_thumbnail is-hidden") %>
                            <% end %>
                        </figure>
                    </div>
                    <div class="card-content is-flex-grow-1 p-0">
                        <div class="content h-100 is-flex is-justify-content-space-between position-relative">
                            <div class="is-flex is-flex-grow-1">
                                <div class="card-title-holder px-4 py-2 is-flex is-flex-direction-column is-justify-content-space-between">
                                    <div class="">
                                        <p class="subject-header is-6 mb-0 color-dark-grey"><%= @premium_course.subject.gsub("_", " ") %></p>
                                        <p class="card-title subtitle mb-1 is-5 has-text-weight-normal"><%= @premium_course.title %></p>
                                        <div class="is-flex is-align-items-center is-justify-content-space-between">
                                            <p class="subtitle is-6 mb-2 color-dark-grey">
                                                <span>by <%= @course_designer.display_name %></span>
                                                <span class="px-1">&middot;</span>
                                                <span><%= @premium_course.created_at.strftime("%Y") %></span>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="is-flex m-0 w-100">
                                        <div class="is-flex is-align-items-baseline pr-5">
                                            <div class="is-size-5 pr-1"><%= @premium_course.quizzes_count %></div>
                                            <div class="color-dark-grey mt-minus-2">quizzes</div>
                                        </div>
                                        <div class="is-flex is-align-items-baseline ">
                                            <div class="is-size-5 pr-1"><%= @premium_course.videos_count %></div>
                                            <div class="color-dark-grey mt-minus-2">videos</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        <% end %>
        <% if @premium_course %>
            <p class="subtitle my-3 py-2">
                Get unlimited access to <span class="has-text-weight-semibold"><%= @premium_course.title %></span> and other premium courses.  
            </p>
        <% else %>
            <p class="subtitle my-5 py-2">
                Get unlimited access to all videography, video editing and sound production courses.  
            </p>
        <% end %>
        <% if logged_in_as_student? %>
            <%= link_to "Subscribe now", checkout_url(subdomain: false), class: "button is-link hero-button"%>
        <% else %>
            <%= link_to "Subscribe now", premium_url(subdomain: false, nbp: "guest"), class: "button is-link hero-button"%>
        <% end %>            
        <div class="is-flex-wrap-wrap is-justify-content-center is-flex my-5 is-size-5 has-text-weight-light">
            <span>$9.99/per month</span>
            <span class="px-3">&#183;</span>
            <span>Cancel Anytime</span>
            <span class="px-3">&#183;</span>
            <span>Recurring billing</span>
        </div>
    </div>
</section>

app/views/subscriptions/payment_error.js.erb
alert("Error!");