config/routes.rb
Rails.application.routes.draw do
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'

    get '/signup', to: 'students#new'

    resource :faq, only: [] do
        get :winning
        # get :competitions
    end

    resource :my_notebook, only: [] do
        get :courses_in_progress
        get :courses_completed
        get :saved_for_later
        get :payment_details

        get :competitions_current
        get :competitions_past
        get :competitions_saved

        get "courses_completed/:course_id_token/show_results", 
            to: "my_notebooks#show_results", as: "show_course_results"
        # get "courses_in_progress/:course_id_token/show_results", to: "my_notebooks#show_results"

        get :basic_info
        get :password_and_email
        get :bio_and_qualifications
        get :messages
        
        namespace :basic_info do 
          patch "update-display-name"
          patch "update-password"
          patch "update-email"
          patch "disable-account"
          patch "delete-account"
          get "delete-account", to: "my_notebooks#show_delete_account"
          get "show-delete-modal"
        end
    end

    root to: 'competitions#index'

    resources :notifications, only: [] do
        member do 
            patch :read          
        end
    end

    resources :video_submissions, shallow: true, only: [] do
        resources :comments, shallow: true, only: [:create, :destroy, :update] do 
          member do 
              post :create_reply
              post :upvote
              delete :upvote, to: "comments#remove_upvote"
          end
        end
    end

    resources :competitions, only: [:index, :show] do
        collection do
            get :paid
            get :volunteer
        end
        member do 
            post :join
            delete :withdraw
        end
        resource :save_event, only: [:create, :destroy]
        resources :comments, shallow: true, only: [:create] do 
          #member do 
          #    post :create_reply
          #end
        end

        resources :video_submissions, shallow: true, only: [:show, :create, :edit, :update, :destroy] do
          collection do
              post :upload_video
          end

          member do 
              patch :upload_video
              post :upvote
              delete :upvote, to: "video_submissions#remove_upvote"
          end
        end
    end

    resources :courses, param: :course_token, only: [:index, :show] do
       member do

          post "like", to: "api/v1/like_event#create_like"
          post "remove_like", to: "api/v1/like_event#destroy"

          post "dislike", to: "api/v1/like_event#create_dislike"
          post "remove_dislike", to: "api/v1/like_event#destroy"

          post "load_slider_notes", to: "courses#load_slider_notes"
       end
    end

    resources :courses, param: :token, only: [] do
       resources :comments, shallow: true, only: [:create, :destroy]

       resource :save_event, only: [:create, :destroy]
    end

    get "/subjects/:subject/", to: "courses#index_by_subject", as: "index_by_subject"
    get "/courses/:course/", to: "courses#index_by_course", as: "index_by_course"

    get '/account_recovery', to: 'students#account_recovery'

    # get "/premium", to: "subscriptions#offer"
    # get "/payment_success", to: "subscriptions#payment_success"

    resource :subscription, only: [] do
        collection do 
            get :show
            post :create
            delete :destroy, path: "/unsubscribe"
            post :update_card
        end
    end

    get "/checkout", to: "subscriptions#checkout", as: "checkout"
    # post "/checkout_session", to: "shopping_cart#checkout_session", as: "checkout_session"

    # post '/checkout/pay', to: 'transaction#create', as: "transaction_create" 
    # get '/checkout/success', to: 'transaction#success', as: "transaction_success"
    # get '/checkout/show', to: 'transaction#show', as: "transaction_show"

    resources :students, param: :student_username, only: [:new, :create, :index] do
      member do
        get :about
        patch :update_photo
        post :billing_address, to: "billing_addresses#create" 
        patch :billing_address, to: "billing_addresses#update"

        post :bank_account, to: "bank_accounts#create"
        patch :bank_account, to: "bank_accounts#update"
      end
    end

    get "/students/not_me/:email_code", to: "students#not_me", as: "not_me"
    get "/students/new_reset_password/:email_code", to: "students#new_reset_password", as: "new_reset_password"

    namespace :api do
      namespace :v1 do
        get 'accounts/:student_id/verify_email', to: 'accounts#verify_email', as: 'verify_email'
        post 'accounts/:student_id/verify_email', to: 'accounts#verify_email', as: 'pin_verify_email'
        get 'accounts/:student_id/check_username_available', to: 'accounts#check_username_available'
        get 'accounts/:student_id/change_email', to: 'accounts#change_email'

        post 'accounts/recover_username', to: 'accounts#recover_username', as: 'recover_username'
        post 'accounts/reset_password', to: 'accounts#reset_password', as: 'reset_password'
        patch 'accounts/create_reset_password', to: 'accounts#create_reset_password', as: 'create_reset_password' # since this is an update
        post 'accounts/not_me_confirmation', to: 'accounts#not_me_confirmation', as: 'not_me_confirmation'

        get 'accounts/reset_password_confirmation', to: 'accounts#reset_password_confirmation', as: 'reset_password_confirmation'
        get 'accounts/not_me', to: 'accounts#not_me', as: 'not_me'
      end
    end
  # go to session controller to switch to dashboard
  # get '/switch_to_dashboard', to: 'sessions#switch_to_dashboard', as: 'switch_to_dashboard'
  # create a subdomain for a student dashboard
  # replacement for generic show route

  constraints :subdomain => 'dashboard' do

    namespace(:dashboard, :path => '/') do

      delete '/logout', to: 'sessions#destroy', as: 'logout'

      get 'orders/new'
      get 'orders/create'
      get 'orders/index'
      post '/courses', to: "private_courses#create"
      patch "/lessons/intro_summary", to: "lessons#update_intro_summary", as: 'update_intro_summary'

      resources :students, controller: :student_admins, param: :student_username, only: [] do
        member do
          patch :update_email
          get :profile
        end
      end

      resources :courses, controller: :private_courses, param: :course_id_token, only: [] do
          member do
            patch :update_module_order
            patch :update_lesson_order # since many modules are affected
          end
      end

      resources :courses, param: :id_token, only: [] do
          resources :module_parts, param: :module_id, shallow: true, only: [:create, :update, :destroy] do
          end
      end

      resources :modules, controller: :module_parts, only: [] do 
            resources :lessons, param: :lesson_id, shallow: true, only: [:create, :edit, :update, :destroy] do
            end
      end

      resources :lessons, only: [] do
            resources :mc_quiz_questions, shallow: true, only: [:create, :edit, :update, :destroy] do
            end
      end

      resources :video_submissions, only: [], shallow: true do
        member do 
          patch :rate
        end
      end

      resources :students, controller: :student_admins, param: :username, only: [] do

            get :payment_history, to: "student_admins#show_payment_history"

            get :comments

            resources :competitions, controller: :private_competitions, except: [:show], shallow: true do
                collection do
                  post :upload_video
                end

                member do 
                  get :video_submissions
                  patch :announce_winners
                end
            end

            resources :courses, controller: :private_courses, param: :course_id_token, only: [], shallow: true do
              collection do
                get :courses, path: "/", as: "content"

                get "/new", to: "private_courses#courses"
                post :create, path: "/"
              end

              member do
                # all options in the tabs for courses.
                get :edit # first option
                get :analytics
                get :design
                get :intro_summary
                # get :comments second option, view comments.

                patch :update, path: "/"
                delete :destroy, path: "/" # last option
                get :delete
              end
            end

            #resource :my_drive, controller: :private_notes, only: [], shallow: true do
            #  collection do
            #    get "/", to: "private_notes#my_drive"
            #    post :load_slider_notes, as: "slider"
            #  end
            #end
      end

    # get :notes, on: :member
      #resources :student_admins, only: [:show, :edit, :update, :destroy]
    end
  end

  constraints :subdomain => 'learning' do
      namespace(:learning, :path => '/') do
          resources :courses, param: :id_token, only: [] do
              patch :update_completed

              get "/lessons/:learnable_type/:learnable_id", to: "lessons#show",
                  as: "lesson", constraints: { 
                  learnable_type: /(lesson-text|lesson-video|mc-quiz|assignment-video)/ 
              }

              get "/lessons/:learnable_type/:learnable_id/:question_id", to: "lessons#show_quiz_question",
                  as: "quiz_question", constraints: { 
                  learnable_type: /(mc-quiz)/ 
              }
              #get "/lesson-texts/:learnable_id", to: "lessons#show_reading", as: "reading"
              #get "/mc-questions/:learnable_id", to: "lessons#show_mc_question", as: "question"

app/models/video_submission.rb
class VideoSubmission < ApplicationRecord
  belongs_to :assignment_video, counter_cache: :video_submissions_count, optional: true

  belongs_to :student
  belongs_to :competition

  has_one_attached :video 

  validates :student_id, uniqueness: { scope: :competition_id, message: "Student already made submission to this competition." }
  has_many :comments, as: :commentable

  has_many :notifications, as: :notifiable
  has_many :upvotes, as: :upvoteable

  validates :upvotes_count, :numericality => { :greater_than_or_equal_to => 0 }
  validates :comments_count, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/dashboard/video_submissions_controller.rb
class Dashboard::VideoSubmissionsController < Dashboard::StudentController

    def rate
        submission = VideoSubmission.find(params[:id])

        if (video_submission_params[:ranking].empty?)
            submission.assign_attributes(ranking: nil, rating: video_submission_params[:rating])
        else 
            submission.assign_attributes(video_submission_params)
        end

        if (submission.save)
            @msg = "Submission has been rated #{submission.rating}"
        else
            @msg = "Submission could not be rated for some reason"        
        end

        respond_to do |format|
            format.js 
        end
    end

    private

    def video_submission_params
        params.fetch(:video_submission).permit(:rating, :ranking)
    end

end

app/controllers/video_submissions_controller.rb
class VideoSubmissionsController < ApplicationController

  before_action :authenticate, only: [:upvote]

  def create
    @competition_id = params[:competition_id].to_i
    @submission = VideoSubmission.create(competition_id: params[:competition_id], student_id: current_student.id,
                                        title: video_submission_params[:title], description: video_submission_params[:description])

    @video = ActiveStorage::Blob.find_by(id: video_submission_key_param[:video_key])
            
    if (@video.present? && @submission.present?)
        @submission.video.purge
        @submission.video.attach(@video) 
        @msg = "Video successfully submitted!"
    else
        @msg = "Video could not be submitted"
    end

    respond_to do |format|
        format.js
    end
  end

  def show
    @video_submission = VideoSubmission.find(params[:id])
    @video_submission_video = @video_submission.video

    @competition = @video_submission.competition
    @video = @competition.video
    @student = @competition.student

    @array_of_contestant_ids = @competition.competition_events.pluck(:student_id)

    if (logged_in_as_student?)
        @student_upvoted_comment_ids = current_student&.upvotes.where(upvoteable_type: "Comment").pluck(:upvoteable_id)
        @student_upvoted_video_ids = current_student&.upvotes.where(upvoteable_type: "VideoSubmission").pluck(:upvoteable_id)
    end

    all_comments = @video_submission.comments.order(created_at: :desc)
    my_comments = all_comments.where(student_id: current_student&.id)
    other_comments = all_comments.excluding(my_comments)

    @comments = my_comments + other_comments 

    if @comments.present?
        @comment_authors = @comments.map(&:student)
        @comment_replies = @comments.map(&:comments)
        @comment_reply_authors = @comment_replies.map{ |collection| collection.map(&:student) if collection.present? }
    end

    @more_submissions = @competition.video_submissions
    @submission_students = @more_submissions.map(&:student)
    @submission_videos = @more_submissions.map(&:video)

    @more_competitions = Competition.find((Competition.pluck(:id) - [@competition.id]).sample(4))
    @competition_students = @more_competitions.map(&:student)
    @competition_videos = @more_competitions.map(&:video)


    respond_to do |format|
        format.html
    end
  end

  def edit
    @video_submission = VideoSubmission.find(params[:id])
    @video = @video_submission.video

    respond_to do |format|
        format.js
    end
  end

  def upload_video
    return true
  end

  def update
    video_submission = VideoSubmission.find(params[:id])
    video = video_submission.video 

    video_submission.update(video_submission_params)

    if (video.blob_id != video_submission_key_param[:video_key].to_i) # video not updated
        @new_video = ActiveStorage::Blob.find(video_submission_key_param[:video_key])

        video.purge
        video.attach(@new_video) 
    end

    respond_to do |format|
        format.js
    end
  end

  def upvote
      video_submission = VideoSubmission.find(params[:id])
      video_submission.increment!(:upvotes_count)

      upvote = Upvote.new(upvoteable_type: "VideoSubmission", upvoteable_id: params[:id], student_id: current_student.id)      
      @saved = upvote.save

      respond_to do |format|
          format.js
      end
  end

  def remove_upvote 
      video_submission = VideoSubmission.find(params[:id])
      video_submission.decrement!(:upvotes_count)

      upvote = Upvote.find_by(upvoteable_type: "VideoSubmission", upvoteable_id: params[:id], student_id: current_student.id)      
      @destroyed = upvote.destroy

      respond_to do |format|
          format.js
      end
  end

  def destroy
  end

  def video_submission_params
      params.fetch(:video_submission).permit(:title, :description)
  end

  def video_submission_key_param
      params.fetch(:video_submission).permit(:video_key)
  end
end

app/helpers/video_submissions_helper.rb
module VideoSubmissionsHelper
end

app/views/video_submissions/_edit.html.erb
<div class="card h-100">
    <header class="card-header">
      <div class="card-header-title py-0 is-justify-content-space-between">
        <div class="py-3">
            <span class="v-align-sub">Update your submission:</span>
            <span class="v-align-sub has-text-weight-normal pl-1"></span>
        </div>
        <i class="fas fa-times fa-lg m-close blue-close"></i>
      </div>
    </header>
    <div class="alert pb-2 mx-2 is-hidden">
      <div class="notification is-danger p-2 mt-4 mx-4">
        <span class="delete"></span>
        <span class="text_holder"></span>
      </div>
    </div>
    <div class="card-content columns m-0 p-0" id="upload_video_submission_modal">
            <%= form_with(model: video_submission, url: upload_video_video_submission_url(id: video_submission.id), 
                local: false, class: "video_file_submission", id: "update_video_submission") do |f| %>
                    <div class="control file file_upload is-boxed w-100 p-2">
                        <div class="video-delete-bar is-justify-content-end opacity-25">
                            <button type="button" class="delete delete-video"></button>
                        </div>
                        <label class="file-label w-100 h-100 p-2">
                            <%= f.file_field :video, direct_upload: true, class:"file-input optional", 
                                id: "new_video_submission_input", type: "file", accept:"video/*" %>
                                <span class="border-radius-none file-cta h-100 is-flex is-justify-content-center">
                                    <figure class="image w-100 is-flex is-hidden h-25vh border is-align-items-center is-justify-content-center position-relative">
                                        <%= image_tag(image_path("AssignmentVideo.png"), class: "h-50", id: "blank_image_holder") %>
                                    </figure>
                                    <span class="file-label is-size-4 is-hidden">
                                        Upload your video
                                    </span>
                                    <%= video_tag rails_blob_path(video), controls: true, class: 'video-player' %>
                                    <div class="pt-4 below-video-info w-100">
                                        <span class="video-title is-size-6"><%= video.filename.to_s %></span>
                                    </div>
                                </span>
                                <progress class="progress border-radius-none is-success is-small is-hidden" value="0" max="100"></progress>
                        </label>
                    </div>
                    <footer class="card-footer is-justify-content-flex-end is-align-items-center">
                        <button id="edit_details" class="button is-link w-min-content">Edit details</button>
                        <%= f.submit "Upload Video", class: "w-min-content button is-info ml-2 mr-4 my-2", disabled: true %>
                    </footer>
            <% end %>
            <%= form_with(model: video_submission, url: video_submission_url(id: video_submission.id), 
                local: false, class: "is-hidden pt-2 video_submission_form", id: "update_video_submission_form") do |f| %>
                <div class="columns m-0 px-1">
                    <div class="column is-half">
                        <div class="field">
                            <div class="control file file_upload input is-boxed h-100">
                                <%= video_tag rails_blob_path(video), controls: true, class: 'video-player-two' %>
                            </div>
                        </div>
                        <%= f.hidden_field :video_key, value: video.blob_id %>
                        <div class="field">
                            <%= f.label :title, class:"label" %>
                            <div class="control">
                                <%= f.text_field :title, class:"input", data: { missing_error: "Please enter a valid title" } %>
                            </div>
                            <p class="help is-danger"></p>
                        </div>
                    </div>
                    <div class="column is-half">
                        <div class="field h-100 is-flex is-flex-direction-column">
                            <%= f.label :description, class:"label" %>
                            <div class="control is-flex-grow-1">
                                <%= f.text_area :description, class:"input optional h-100", data: { missing_error: "Please enter a valid prize amount" } %>
                            </div>
                            <p class="help is-danger"></p>
                        </div>
                    </div>
                </div>
                 <footer class="card-footer is-justify-content-space-between is-align-items-center">
                    <div class="upload_modal_progress mx-5 is-align-items-center is-flex is-invisible">
                        <p class="w-100 upload_updates"></p>
                        <progress class="mx-4 mb-0 progress is-primary" value="0" max="100"></progress>
                        <div class="css-loader is-hidden mx-4"></div>
                    </div>
                    <%= f.submit "Update submission", class: "w-min-content button is-link mx-4 my-2" %>
                </footer>
            <% end %>
    </div>
</div>
 <!--
    <footer class="card-footer is-justify-content-space-between is-align-items-center">
      <div id="upload_modal_progress" class="mx-5 is-align-items-center is-flex is-invisible">
        <p id="upload_updates" class="w-100"></p>
        <progress class="mx-4 mb-0 progress is-primary" value="0" max="100"></progress>
        <div class="css-loader is-hidden mx-4"></div>
      </div>
      <button id="new_video_submission_upload_button" class="w-min-content button is-link mx-4 my-2" data-disable-with="Upload">
        Upload Video
      </button>
    </footer>
    -->

app/views/video_submissions/_my_submission.html.erb
<%= link_to video_submission_url(subdomain: false, id: video_submission.id), class: "show-submission-link w-100 is-flex" do %>
        <div class="card-image">
            <figure class="image w-100">
                <% if video_submission_video.previewable? %>
                    <%= image_tag video_submission_video.preview(resize_to_limit: [300, 200]),  
                        class:"course_image_thumbnail border-radius-none" %>
                <% else %>
                    <%= image_tag(image_path("image_placeholder.png"), class:"course_image_thumbnail obj-cover border-radius-none") %>
                <% end %>
            </figure>
        </div>
        <div class="card-content py-2 pl-4 pr-0 is-flex-grow-1">
            <div class="field">
                <label class="label">Title:</label>
                <div class="control">
                    <span id="my_submission_title"><%= video_submission.title %></span>
                </div>
            </div>
            <div class="field h-100 is-flex is-flex-direction-column">
                <label class="label">Description:</label>
                <div class="control is-flex-grow-1">
                    <span id="my_submission_description"><%= video_submission.description %></span>
                </div>
            </div>
        </div>
<% end %>

app/views/video_submissions/_new.html.erb
<div class="card h-100">
    <header class="card-header">
      <div class="card-header-title py-0 is-justify-content-space-between">
        <div class="py-3">
            <span class="v-align-sub">Competition:</span>
            <span class="v-align-sub has-text-weight-normal pl-1"><%= competition.title %></span>
        </div>
        <i class="fas fa-times fa-lg m-close blue-close"></i>
      </div>
    </header>
    <div class="alert pb-2 mx-2 is-hidden">
      <div class="notification is-danger p-2 mt-4 mx-4">
        <span class="delete"></span>
        <span class="text_holder"></span>
      </div>
    </div>
    <div class="card-content columns m-0 p-0" id="upload_video_submission_modal">
            <%= form_with(scope: :video_submission, url: upload_video_competition_video_submissions_url(competition_id: competition.id), 
                local: false, class: "video_file_submission", id: "upload_video_submission") do |f| %>
                    <div class="control file file_upload is-boxed w-100 p-2">
                        <div class="video-delete-bar is-hidden is-justify-content-end opacity-25">
                            <button type="button" class="delete delete-video"></button>
                        </div>
                        <label class="file-label w-100 h-100 p-2">
                            <%= f.file_field :video, direct_upload: true, class:"file-input optional", 
                                id: "new_video_submission_input", type: "file", accept:"video/*" %>
                                <span class="border-radius-none file-cta h-100 is-flex is-justify-content-center">
                                <figure class="image w-100 is-flex h-25vh border is-align-items-center is-justify-content-center position-relative">
                                    <%= image_tag(image_path("AssignmentVideo.png"), class: "h-50", id: "blank_image_holder") %>
                                </figure>
                                <span class="file-label is-size-4">
                                    Upload your video
                                </span>
                                <video controls class="video-player is-hidden">Your browser does not support the video tag.</video>
                                <div class="pt-4 below-video-info w-100">
                                    <span class="video-title is-size-6"></span>
                                </div>
                                </span>
                                <progress class="progress border-radius-none is-success is-small is-hidden" value="0" max="100"></progress>
                        </label>
                    </div>
                    <footer class="card-footer is-justify-content-flex-end is-align-items-center">
                        <%= f.submit "Upload Video", class: "w-min-content button is-link mx-4 my-2" %>
                    </footer>
            <% end %>
            <%= form_with(scope: :video_submission, url: competition_video_submissions_url(competition_id: competition.id), 
                local: false, class: "is-hidden pt-2 video_submission_form", id: "upload_video_submission_form") do |f| %>
                <div class="columns m-0 px-1">
                    <div class="column is-half">
                        <div class="field">
                            <div class="control file file_upload input is-boxed h-100">
                                <video src="#" controls class="video-player-two">
                                    Your competition does not support the video tag.
                                </video> 
                            </div>
                        </div>
                        <%= f.hidden_field :video_key %>
                        <div class="field">
                            <%= f.label :title, class:"label" %>
                            <div class="control">
                                <%= f.text_field :title, class:"input", data: { missing_error: "Please enter a valid title" } %>
                            </div>
                            <p class="help is-danger"></p>
                        </div>
                    </div>
                    <div class="column is-half">
                        <div class="field h-100 is-flex is-flex-direction-column">
                            <%= f.label :description, class:"label" %>
                            <div class="control is-flex-grow-1">
                                <%= f.text_area :description, class:"input optional h-100", data: { missing_error: "Please enter a valid prize amount" } %>
                            </div>
                            <p class="help is-danger"></p>
                        </div>
                    </div>
                </div>
                 <footer class="card-footer is-justify-content-space-between is-align-items-center">
                    <div class="upload_modal_progress mx-5 is-align-items-center is-flex is-invisible">
                        <p class="w-100 upload_updates"></p>
                        <progress class="mx-4 mb-0 progress is-primary" value="0" max="100"></progress>
                        <div class="css-loader is-hidden mx-4"></div>
                    </div>
                    <%= f.submit "Upload Video", class: "w-min-content button is-link mx-4 my-2" %>
                </footer>
            <% end %>
    </div>
</div>
 <!--
    <footer class="card-footer is-justify-content-space-between is-align-items-center">
      <div id="upload_modal_progress" class="mx-5 is-align-items-center is-flex is-invisible">
        <p id="upload_updates" class="w-100"></p>
        <progress class="mx-4 mb-0 progress is-primary" value="0" max="100"></progress>
        <div class="css-loader is-hidden mx-4"></div>
      </div>
      <button id="new_video_submission_upload_button" class="w-min-content button is-link mx-4 my-2" data-disable-with="Upload">
        Upload Video
      </button>
    </footer>
    -->

app/views/video_submissions/create.js.erb
if ($("#show_competition_container").length == 1) {
    if ($("#my-notebook-page-holder").length == 1) {
        // uploaded new submission from the user my notebook panel.
        var competition_card = $("#show_competition_container")
          .find(".card[data-competition-id='<%= @competition_id %>']");
        competition_card.find("span.new-submission-button").remove();
        competition_card.find(".course-options")
          .prepend('<a class="is-link button mb-2 resume-button w-100" href="<%= video_submission_url(subdomain: false, id: @submission.id) %>">Review submission</a>');
        competition_card.find(".modal.is-active").removeClass("is-active");
    } else {
        // uploaded new submission from the competition show page.
        $("#show_competition_container .modal.is-active").removeClass("is-active");
        console.log($("#my_submission .card-holder"));
        $("#my_submission .card-holder").html('<%= j render("my_submission", video_submission: @submission, video_submission_video: @video) %>');
        $("section#header_box .tabs li[data-content-link='my-submission']").removeClass("is-hidden");

        $("#header_box #upload_video_submission_button").remove();
        $("#edit_submission_button").removeClass("is-hidden").attr('<%= edit_video_submission_url(id: @submission.id) %>');
    }
} else {
    $("#video_submissions > .modal.is-active").removeClass("is-active");
    $("#my-notebook-page-holder .card > .modal.is-active").removeClass("is-active");
}

var snackbar = document.createElement("div");
$(snackbar).attr("id", "snackbar");
$(snackbar).text("<%= @msg %>");
$("body").append($(snackbar));
$(snackbar).addClass("show");
setTimeout(
  function(){
    $(snackbar).removeClass("show");
  }, 4000);

app/views/video_submissions/destroy.js.erb
<h1>VideoSubmissions#destroy</h1>
<p>Find me in app/views/video_submissions/destroy.html.erb</p>

app/views/video_submissions/edit.js.erb
$("#update_video_submission_modal_body").html("<%= j render 'video_submissions/edit', video_submission: @video_submission, video: @video %>");

$("#my_submission .modal").addClass("is-active");

app/views/video_submissions/remove_upvote.js.erb
var upvote_box = $("#show-video-player .video-submission-buttons button.upvote-box");       
var upvote_icon = upvote_box.find("i");
var upvote_counter = upvote_box.find(".upvote-counter");

if (upvote_icon.hasClass("upvoted")) { 
    upvote_icon.removeClass("upvoted");
    upvote_counter.text(parseInt(upvote_counter.text()) - 1);
    upvote_icon.parent().attr("data-method", "post");
}

app/views/video_submissions/update.html.erb
<h1>VideoSubmissions#update</h1>
<p>Find me in app/views/video_submissions/update.html.erb</p>