config/routes.rb
        get :saved_for_later
        get :payment_details

        get :competitions_current
        get :competitions_past
        get :competitions_saved

        get "courses_completed/:course_id_token/show_results", 
            to: "my_notebooks#show_results", as: "show_course_results"
        # get "courses_in_progress/:course_id_token/show_results", to: "my_notebooks#show_results"

        get :basic_info
        get :password_and_email
        get :bio_and_qualifications
        get :messages
        
        namespace :basic_info do 
          patch "update-display-name"
          patch "update-password"
          patch "update-email"
          patch "disable-account"
          patch "delete-account"
          get "delete-account", to: "my_notebooks#show_delete_account"
          get "show-delete-modal"
        end
    end

    root to: 'competitions#index'

    resources :notifications, only: [] do
        member do 
            patch :read          
        end
    end

    resources :video_submissions, shallow: true, only: [] do
        resources :comments, shallow: true, only: [:create, :destroy, :update] do 
          member do 
              post :create_reply
              post :upvote
              delete :upvote, to: "comments#remove_upvote"
          end
        end
    end

    resources :competitions, only: [:index, :show] do
        collection do
            get :paid
            get :volunteer
        end
        member do 
            post :join
            delete :withdraw
        end
        resource :save_event, only: [:create, :destroy]
        resources :comments, shallow: true, only: [:create] do 
          #member do 
          #    post :create_reply
          #end
        end

        resources :video_submissions, shallow: true, only: [:show, :create, :edit, :update, :destroy] do
          collection do
              post :upload_video
          end

          member do 
              patch :upload_video
              post :upvote
              delete :upvote, to: "video_submissions#remove_upvote"
          end
        end
    end

    resources :courses, param: :course_token, only: [:index, :show] do
       member do

          post "like", to: "api/v1/like_event#create_like"
          post "remove_like", to: "api/v1/like_event#destroy"

          post "dislike", to: "api/v1/like_event#create_dislike"
          post "remove_dislike", to: "api/v1/like_event#destroy"

          post "load_slider_notes", to: "courses#load_slider_notes"
       end
    end

    resources :courses, param: :token, only: [] do
       resources :comments, shallow: true, only: [:create, :destroy]

       resource :save_event, only: [:create, :destroy]
    end

    get "/subjects/:subject/", to: "courses#index_by_subject", as: "index_by_subject"
    get "/courses/:course/", to: "courses#index_by_course", as: "index_by_course"

    get '/account_recovery', to: 'students#account_recovery'

    # get "/premium", to: "subscriptions#offer"
    # get "/payment_success", to: "subscriptions#payment_success"

    resource :subscription, only: [] do
        collection do 
            get :show
            post :create
            delete :destroy, path: "/unsubscribe"
            post :update_card
        end
    end

    get "/checkout", to: "subscriptions#checkout", as: "checkout"
    # post "/checkout_session", to: "shopping_cart#checkout_session", as: "checkout_session"

    # post '/checkout/pay', to: 'transaction#create', as: "transaction_create" 
    # get '/checkout/success', to: 'transaction#success', as: "transaction_success"
    # get '/checkout/show', to: 'transaction#show', as: "transaction_show"

    resources :students, param: :student_username, only: [:new, :create, :index] do
      member do
        get :about
        patch :update_photo
        post :billing_address, to: "billing_addresses#create" 
        patch :billing_address, to: "billing_addresses#update"

        post :bank_account, to: "bank_accounts#create"
        patch :bank_account, to: "bank_accounts#update"
      end
    end

    get "/students/not_me/:email_code", to: "students#not_me", as: "not_me"
    get "/students/new_reset_password/:email_code", to: "students#new_reset_password", as: "new_reset_password"

    namespace :api do
      namespace :v1 do
        get 'accounts/:student_id/verify_email', to: 'accounts#verify_email', as: 'verify_email'
        post 'accounts/:student_id/verify_email', to: 'accounts#verify_email', as: 'pin_verify_email'
        get 'accounts/:student_id/check_username_available', to: 'accounts#check_username_available'
        get 'accounts/:student_id/change_email', to: 'accounts#change_email'

        post 'accounts/recover_username', to: 'accounts#recover_username', as: 'recover_username'
        post 'accounts/reset_password', to: 'accounts#reset_password', as: 'reset_password'
        patch 'accounts/create_reset_password', to: 'accounts#create_reset_password', as: 'create_reset_password' # since this is an update
        post 'accounts/not_me_confirmation', to: 'accounts#not_me_confirmation', as: 'not_me_confirmation'

        get 'accounts/reset_password_confirmation', to: 'accounts#reset_password_confirmation', as: 'reset_password_confirmation'
        get 'accounts/not_me', to: 'accounts#not_me', as: 'not_me'
      end
    end
  # go to session controller to switch to dashboard
  # get '/switch_to_dashboard', to: 'sessions#switch_to_dashboard', as: 'switch_to_dashboard'
  # create a subdomain for a student dashboard
  # replacement for generic show route

  constraints :subdomain => 'dashboard' do

    namespace(:dashboard, :path => '/') do

      delete '/logout', to: 'sessions#destroy', as: 'logout'

      get 'orders/new'
      get 'orders/create'
      get 'orders/index'
      post '/courses', to: "private_courses#create"
      patch "/lessons/intro_summary", to: "lessons#update_intro_summary", as: 'update_intro_summary'

      resources :students, controller: :student_admins, param: :student_username, only: [] do
        member do
          patch :update_email
          get :profile
        end
      end

      resources :courses, controller: :private_courses, param: :course_id_token, only: [] do
          member do
            patch :update_module_order
            patch :update_lesson_order # since many modules are affected
          end
      end

      resources :courses, param: :id_token, only: [] do
          resources :module_parts, param: :module_id, shallow: true, only: [:create, :update, :destroy] do
          end
      end

      resources :modules, controller: :module_parts, only: [] do 
            resources :lessons, param: :lesson_id, shallow: true, only: [:create, :edit, :update, :destroy] do
            end
      end

      resources :lessons, only: [] do
            resources :mc_quiz_questions, shallow: true, only: [:create, :edit, :update, :destroy] do
            end
      end

      resources :video_submissions, only: [], shallow: true do
        member do 
          patch :rate
        end
      end

      resources :students, controller: :student_admins, param: :username, only: [] do

            get :payment_history, to: "student_admins#show_payment_history"

            get :comments

            resources :competitions, controller: :private_competitions, except: [:show], shallow: true do
                collection do
                  post :upload_video
                end

                member do 
                  get :video_submissions
                  patch :announce_winners
                end
            end

            resources :courses, controller: :private_courses, param: :course_id_token, only: [], shallow: true do
              collection do
                get :courses, path: "/", as: "content"

                get "/new", to: "private_courses#courses"
                post :create, path: "/"
              end

              member do
                # all options in the tabs for courses.
                get :edit # first option
                get :analytics
                get :design
                get :intro_summary
                # get :comments second option, view comments.

                patch :update, path: "/"
                delete :destroy, path: "/" # last option
                get :delete
              end
            end

            #resource :my_drive, controller: :private_notes, only: [], shallow: true do
            #  collection do
            #    get "/", to: "private_notes#my_drive"
            #    post :load_slider_notes, as: "slider"
            #  end
            #end
      end

    # get :notes, on: :member
      #resources :student_admins, only: [:show, :edit, :update, :destroy]
    end
  end

  constraints :subdomain => 'learning' do
      namespace(:learning, :path => '/') do
          resources :courses, param: :id_token, only: [] do
              patch :update_completed

              get "/lessons/:learnable_type/:learnable_id", to: "lessons#show",
                  as: "lesson", constraints: { 
                  learnable_type: /(lesson-text|lesson-video|mc-quiz|assignment-video)/ 
              }

              get "/lessons/:learnable_type/:learnable_id/:question_id", to: "lessons#show_quiz_question",
                  as: "quiz_question", constraints: { 
                  learnable_type: /(mc-quiz)/ 
              }
              #get "/lesson-texts/:learnable_id", to: "lessons#show_reading", as: "reading"
              #get "/mc-questions/:learnable_id", to: "lessons#show_mc_question", as: "question"
              #get "/lesson-videos/:learnable_id", to: "lessons#show_video", as: "video"
              #get "/mc-quiz/:learnable_id/start", to: "lessons#start_quiz", as: "mc_quiz_start"

              patch "/mc-questions/:learnable_id", to: "lessons#update_mc_quiz_answer", as: "mc_quiz_answer"
          end
      end
  end

app/controllers/dashboard/lessons_controller.rb
class Dashboard::LessonsController < Dashboard::StudentController
    layout "design_lesson"
     # create is responsible for saving new lessons and saving the rearrangement of lesson order.
    def create
        @module_id = params[:module_id]
        module_part = ModulePart.find(params[:module_id])
        course = module_part.course     

        current_lesson_order = module_part.lesson_order
        new_lesson_order = new_lesson_params[:lesson_type_order]
        # combine the values of lesson_ids and types into a single string and check for a letter.
        # true if a new lesson was added and false if not.  
        new_lessons_added = !(/[a-zA-Z]/.match(new_lesson_order.reduce(:+)).nil?)
        @new_lesson_counter = 0

        if (new_lessons_added)
            @new_edit_lesson_urls = []
            @lesson_ids = []
                
            new_lesson_order.map! do |string|
                    # iterate over the array of lesson ids to find the new lesson
                    if (/[1-9]/.match(string).nil?) # match is nil means it must be the new lesson inserted.
                        # if a new lesson was inserted, then create a new lesson at that index.
                        lesson_type = string.split("-").map(&:capitalize).join
                        lesson = Lesson.create!(learnable: lesson_type.constantize.new(), module_part_id: params[:module_id])
                        # course lesson type counter increased by 1 after the save.

                        @new_edit_lesson_urls << edit_dashboard_lesson_url(lesson_id: lesson.id, subdomain: "dashboard")
                        @lesson_ids << lesson.id

                        @new_lesson_counter += 1
                        lesson.id
                    else 
                        # convert string lesson id to integer
                        string.to_i
                    end
            end
            module_part.update!(lesson_order: new_lesson_order)
            # once module order has been saved
            # update the course to reflect the change in that new module order
            course_lesson_order = ModulePart.find(course.module_order).map do |module_part|
                module_part.lesson_order
            end
            course_lesson_order.flatten!

            #update both the lesson order array and the lesson length
            course.update(lesson_order: course_lesson_order, 
                        lessons_count: course_lesson_order.length)
            # update_lessons_count
        else # no new lessons added. Thus lessons were only rearranged.
            # convert elements to int
            new_lesson_order.map!(&:to_i)
            if (new_lesson_order == current_lesson_order)
                # do nothing since no lesson has been rearranged.
                # same number of lessons and same lesson order
            else     
                # new lesson rearrangement has been updated to the module.
                # or some lessons have been deleted.
                module_part.update!(lesson_order: new_lesson_order)         
                # @course.update_lessons_count, since the lesson count may be lower now.   
            end
        end

        @lessons_count = new_lesson_order.length
        @course = Course.find(course.id)

        respond_to do |format|
            format.js
        end
    end

    def edit
      @lesson = Lesson.find(params[:lesson_id])    
      @learnable = @lesson.learnable
      @lesson_type = @learnable.class.to_s.underscore.to_sym

      if (@lesson_type == :lesson_video)
          if (@learnable.video.attached?)
              @video_attached = true
              @video = @learnable.video
          end
      elsif (@lesson_type == :mc_quiz)
          @mc_quiz_questions = McQuizQuestion.find(@learnable.question_order)
      end

      @module = @lesson.module_part
      module_lesson_order = @module.lesson_order
      @module_lessons = Lesson.find(module_lesson_order)

      @course = @module.course
      @module_position = @course.module_order.index(@module.id)
      @lesson_position = module_lesson_order.index(@lesson.id)

      respond_to do |format|
        format.html { render "/dashboard/lessons/lesson_type_edits/#{@lesson_type.to_s}_edit" }
      end
    end

    def update
        lesson = Lesson.find(params[:lesson_id])
        learnable = lesson.learnable

        lesson_type = learnable.class.to_s
        @msg = "#{lesson_type} successfully updated!"

        case lesson_type
        when "LessonText"
            learnable.update!(content: lesson_text_params[:content])
            has_content = (lesson_text_params[:content].present?) ? true : false
        when "LessonVideo"
            video = ActiveStorage::Blob.find_by(id: lesson_video_params[:video_key])
            if video.present?
                learnable.video.purge
                learnable.video.attach(video) 
                @msg = "Video successfully uploaded!"
            end
        when "McQuiz"
            if (params.fetch(:lesson).has_key?(:mc_quiz))
                learnable.update!(question_order: lesson_mc_quiz_params[:question_order])
                has_content = true
            else 
                has_content = false 
            end
        when "AssignmentVideo"
            deadline_time = assignment_video_params[:deadline_date] + " " + assignment_video_params[:deadline_time] 
            if (Time.parse(deadline_time).utc < Time.current)
                @msg = "Deadline must not be earlier than the current time"
            else
                learnable.update!(assignment_video_params)            
            end
        end
        if (lesson_params[:title].present? && (lesson_params[:title] != lesson.title))
            lesson.update!(title: lesson_params[:title], has_content: has_content)
        end 
        respond_to do |format|
          format.js
        end
    end

    def update_intro_summary # update either summary or the intro, depending on the lesson id.
        lesson = Lesson.find(params[:lesson_id])
        
        lesson.update!(title: lesson_params[:title])
        lesson.learnable.update!(content: lesson_text_params[:content])

        @message = (lesson_params[:type] == "intro") ? "Introduction" : "Summary" 

        respond_to do |format|
            format.js
        end
    end


    def destroy
        @lesson_id = params[:lesson_id]
        lesson = Lesson.find(params[:lesson_id])

        lesson.destroy!  
        # use as variable to get the updated counters
        @module_part = lesson.module_part
        @course = @module_part.course

        respond_to do |format|
          format.js
        end
    end

    def new_lesson_params
        params.fetch(:module_part).permit(lesson_type_order: [])
    end

    def lesson_params
        params.fetch(:lesson).permit(:title, :type)
    end

    def lesson_text_params
        params.fetch(:lesson).fetch(:lesson_text).permit(:content)
    end

    def lesson_mc_quiz_params
        params.fetch(:lesson).fetch(:mc_quiz).permit(question_order: [])
    end

    def lesson_video_params
        params.fetch(:lesson).permit(:video_key)
    end

    def assignment_video_params
        params.fetch(:lesson).fetch(:assignment_video).permit(:requirements, :prize_money, 
                                               :deadline_date, :deadline_time)
    end
end

app/helpers/dashboard/lessons_helper.rb
module Dashboard::LessonsHelper
end

app/helpers/dashboard/mc_quiz_questions_helper.rb
module Dashboard::McQuizQuestionsHelper
end

app/helpers/dashboard/orders_helper.rb
module Dashboard::OrdersHelper
end

app/helpers/dashboard/private_competitions_helper.rb
module Dashboard::PrivateCompetitionsHelper
end

app/helpers/dashboard/private_notes_helper.rb
module Dashboard::PrivateNotesHelper
end

app/helpers/dashboard/save_event_helper.rb
module Dashboard::SaveEventHelper
end

app/helpers/dashboard/student_admins_helper.rb
module Dashboard::StudentAdminsHelper
end

app/views/dashboard/private_competitions/_competitions_table.html.erb
  <table id="competitions_table" class="table w-100">
    <thead>
      <tr>
        <th>
          <input type="checkbox" class="outline_none mr-2 w-min-content" id="select_note_page_notes">
          <span>Competitions</span>
        </th>
        <th>Deadline</th>
        <th class="has-text-right">Video Submissions</th>
        <th class="has-text-right">Contestants</th>
        <!-- <th class="has-text-right">Comments</th> -->
      </tr>
    </thead>
    <tbody>
      <% competitions.each do |competition| %>
        <tr data-competition-id="<%= competition.id %>">
              <td class="is-flex">
                <label class="checkbox w-min-content is-align-self-center">
                    <input type="checkbox" class="outline_none w-min-content">
                </label>
                <figure class="column image is-justify-content-center is-flex-direction-column">
                    <% if competition.video.previewable? %>
                        <%= image_tag competition.video.preview(resize_to_limit: [210, 150]),  class:"course_image_thumbnail" %>
                    <% else %>
                        <%= image_tag(image_path("image_placeholder.png"), class:"course_image_thumbnail") %>
                    <% end %>
                </figure>
                <div class="column note-column">
                    <p><%= competition.title %></p>
                    <p class="text-secondary is-clipped"><%= competition.subtitle %></p>
                    <div class="note_options is-hidden">
                      <%= link_to edit_dashboard_competition_url(competition.id, subdomain: "dashboard") do %>
                          <i class="fas fa-pencil-alt"></i>
                      <% end %>
                      <%= link_to "#" do %>
                          <i class="far fa-comment-alt"></i>
                      <% end %>
                      <%= link_to video_submissions_dashboard_competition_url(competition.id, subdomain: "dashboard") do %>
                          <i class="fas fa-star"></i>
                      <% end %>
                      <%= link_to dashboard_competition_url(competition.id, subdomain: "dashboard"), method: :delete,
                      class: "", remote: true, data: { confirm: "Are you sure you want to delete this competition?" } do %>
                          <i class="fas fa-trash-alt"></i>
                      <% end %>
                    </div>
                </div>
              </td>
              <td><span><%= local_time(competition.deadline_date).strftime("%d %b, %Y") %></span></td>
              <td><p class="has-text-right"><%= competition.video_submissions.count %></p></td>
              <td><p class="has-text-right"><%= competition.contestants.count %></p></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= pagy_bulma_nav(pagy).html_safe %>

app/views/dashboard/private_competitions/_new.html.erb
<div class="card h-100">
    <header class="card-header">
      <div class="card-header-title py-0 is-justify-content-space-between">
        <span class="py-4">Create a Competition</span>
        <i class="fas fa-times fa-lg m-close blue-close"></i>
      </div>
    </header>
    <div class="alert pb-2 mx-2 is-hidden">
      <div class="notification is-danger p-2 mt-4 mx-4">
        <span class="delete"></span>
        <span class="text_holder"></span>
      </div>
    </div>
    <div class="card-content columns my-2 mx-0 px-1 py-0" id="upload_competition_modal">
            <%= form_with(scope: :competition, url: upload_video_dashboard_student_competitions_url(subdomain: "dashboard", student_username: current_student.username), 
                local: false, class: "is-flex w-100 p-1", id: "upload_video") do |f| %>
                    <div class="control file file_upload is-boxed w-100 mx-2">
                        <div class="video-delete-bar is-hidden is-justify-content-end opacity-25">
                            <button type="button" class="delete delete-video"></button>
                        </div>
                        <label class="file-label w-100 h-100">
                            <%= f.file_field :video, direct_upload: true, class:"file-input optional", 
                                id: "new_competition_video_input", type: "file", accept:"video/*" %>
                                <span class="border-radius-none file-cta h-100 is-flex is-justify-content-center">
                                <figure class="image w-100 is-flex h-25vh border is-align-items-center is-justify-content-center position-relative">
                                    <%= image_tag(image_path("AssignmentVideo.png"), class: "h-50", id: "blank_image_holder") %>
                                </figure>
                                <span class="file-label is-size-4">
                                    Upload a video
                                </span>
                                <video controls class="video-player is-hidden">Your browser does not support the video tag.</video>
                                <div class="pt-4 below-video-info w-100">
                                    <span class="video-title is-size-6"></span>
                                </div>
                                </span>
                                <progress class="progress border-radius-none is-success is-small is-hidden" value="0" max="100"></progress>
                        </label>
                    </div>
            <% end %>
            <%= form_with(scope: :competition, url: dashboard_student_competitions_url(subdomain: "dashboard", student_username: current_student.username), 
                local: true, class: "is-flex is-hidden w-100 pt-2", id: "upload_competition_form") do |f| %>
                <div class="column is-half">
                    <div class="field">
                        <div class="control file file_upload input is-boxed h-100">
                            <video src="#" controls class="video-player-two">
                                Your competition does not support the video tag.
                            </video> 
                        </div>
                    </div>
                    <%= f.hidden_field :video_key %>
                    <div class="field">
                          <%= f.label :title, class:"label" %>
                          <div class="control">
                             <%= f.text_field :title, class:"input", data: { missing_error: "Please enter a valid title" } %>
                          </div>
                          <p class="help is-danger"></p>
                    </div>
                    <div class="field">
                        <%= f.label :start_date, class:"label" %>
                        <div class="control">
                            <%= f.date_field :start_date, class:"input", data: { missing_error: "Please enter a valid date" } %>
                        </div>
                        <p class="help is-danger"></p>
                    </div>
                    <!--
                    <div class="field">
                        <%= f.label :prize_money, class:"label" %>
                        <div class="control has-icons-left">
                            <%= f.number_field :prize_money, class:"input", readonly: true,
                                value: 0, data: { missing_error: "Please enter a valid prize amount" } %>
                            <span class="icon is-small is-left">
                                 <i class="fas fa-dollar-sign"></i>
                            </span>
                        </div>
                        <p class="help is-danger"></p>
                    </div>
                    -->
                </div>
                <div class="column is-half">
                      <div class="field">
                            <%= f.label :deadline_date, class:"label" %>
                            <div class="control">
                                <%= f.date_field :deadline_date, class:"input", data: { missing_error: "Please enter a valid date" } %>
                            </div>
                            <p class="help is-danger"></p>
                      </div>
                      <div class="field">
                            <%= f.label :results_date, class:"label" %>
                            <div class="control">
                                <%= f.date_field :results_date, class:"input", data: { missing_error: "Please enter a valid date" } %>
                            </div>
                            <p class="help is-danger"></p>
                      </div>
                      <!--
                      <div class="field">
                            <%= f.label :deadline_time, class:"label" %>
                            <div class="control">
                                <%= f.time_field :deadline_time, class:"input", data: { missing_error: "Please enter a valid time" } %>
                            </div>
                            <p class="help is-danger"></p>
                      </div> -->
                      <div class="field subtitle">
                            <%= f.label :subtitle, class: "label pr-0" %>
                            <div class="control">
                                <%= f.text_area :subtitle, class: "textarea", data: { missing_error: "Please enter a valid subtitle" } %>
                            </div>
                            <p class="help is-danger"></p>
                      </div>
                </div>
            <% end %>
    </div>
    <footer class="card-footer is-justify-content-space-between is-align-items-center">
      <div id="upload_modal_progress" class="mx-5 is-align-items-center is-flex is-invisible">
        <p id="upload_updates" class="w-100"></p>
        <progress class="mx-4 mb-0 progress is-primary" value="0" max="100"></progress>
        <div class="css-loader is-hidden mx-4"></div>
      </div>
      <button id="new_competition_upload_button" class="w-min-content button is-link mx-4 my-2" data-disable-with="Upload">
        Upload Video
      </button>
    </footer>
</div>

app/views/dashboard/private_competitions/announce_winners.js.erb
// display a popup indicating update success.
var snackbar = document.createElement("div");
$(snackbar).attr("id", "snackbar");
$(snackbar).text("<%= @msg %>");
$("body").append($(snackbar));
$(snackbar).addClass("show");
setTimeout( function(){ 
    $(snackbar).removeClass("show"); 
}, 4000);

app/views/dashboard/private_competitions/create.html.erb
<h1>Dashboard::PrivateCompetitions#create</h1>
<p>Find me in app/views/dashboard/private_competitions/create.html.erb</p>

app/views/dashboard/private_competitions/destroy.js.erb
// display a popup indicating update success.
var snackbar = document.createElement("div");
$(snackbar).attr("id", "snackbar");
$(snackbar).text("<%= @message %>");
$("body").append($(snackbar));
$(snackbar).addClass("show");
setTimeout( function(){ $(snackbar).removeClass("show"); }, 4000);

app/views/dashboard/private_competitions/index.html.erb
<aside class="menu pt-0 px-4" id="dashboard_sidebar">
    <div id="aside_header" class="py-4">
        <span>Instructor dashboard</span>
    </div>
    <ul class="menu-list" id="student-menu-list">
        <li><%= link_to "Competitions", dashboard_student_competitions_url(current_student.username), class: "is-active" %></li>            
        <li><%= link_to "Courses", content_dashboard_student_courses_url(current_student.username) %></li>
    </ul>
</aside>
<div id="index-dashboard-body" class="flex-grow w-100 is-flex is-flex-direction-column">
    <div class="dashboard-panel is-flex-grow-1">
      <section class="section pt-4 pb-2">
          <div class="container is-flex is-justify-content-space-between">
            <h1 class="title is-4 mb-0">Competitions</h1>
            <div class="left-side is-flex h-min-content">
                <div class="field has-addons">
                  <div class="control">
                    <input class="input is-sl-small" type="text" placeholder="Search uploads, notes...">
                  </div>
                  <div class="control">
                    <a class="button is-info is-sl-small">
                      <i class="fas fa-search"></i>
                    </a>
                  </div>
                </div>
              </div>
          </div>
      </section>
    <!--  <section class="section py-2">
        <div class="container">
          <div class="tabs">
            <ul>
              <li class="is-active"><a>Purchases</a></li>
              <li><a>Bookmarked</a></li>
            </ul>
          </div>
        </div>
      </section> -->
      <section class="section py-0">
        <div class="container">
              <div id="competition_holder" class="is-flex is-align-items-center" data-selected-counter="0" data-total-uploads=<%= @created_competitions.count.to_s %>>
                  <span class="number_results"><%= pluralize(@competitions.count, "competition") %> uploaded</span>
                  <span class="px-2 is-hidden" id="select_all_notes_link">
                    (<span class="has-text-link cursor_pointer">
                      Select All
                    </span>)
                  </span>
                  <span class="is-hidden is-flex" id="results_selected_actions">
                      <span class="mx-2">&#124;</span>
                      <button type="button" class="button is-small">Download</button>
                      <button type="button" class="button is-small">Delete</button>
                  </span>
              </div>    
        </div>
      </section>
      <section class="section py-2" id="competitions_table_section">
        <%= render "competitions_table", competitions: @created_competitions, pagy: @pagy  %>
      </section>
    </div>
</div>